apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato-clone
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: zomato-clone
  template:
    metadata:
      labels:
        app: zomato-clone
    spec:
      containers:
      - image: jaideep29/zomato:zomato-clone
        name: zomato-clone
        ports:
        - containerPort: 80